config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :passed_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create] do
    get :new
    post :create
  end

  resources :badges, only: :index

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/passed_test.rb
class PassedTest < ApplicationRecord
  TEST_SUCCESS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true, foreign_key: 'current_question'

  before_validation :before_validation_set_next_question

  scope :by_category, ->(category){
    joins(:test).where(tests: { category: category })
  }

  scope :by_level, ->(level){
    joins(:test).where(tests: { level: level })
  }

  def accept!(answer_ids)
    return if answer_ids.nil?

    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.save!
  end

  def completed?
    current_question.nil?
  end

  def rate_percentage
    completed? ? ((self.correct_questions.to_f / questions_count) * 100).to_i : 0
  end

  def question_number
    test.questions.order(id: :asc).pluck(:id).index(current_question.id) + 1
  end

  def questions_count
    test.questions.count
  end

  private

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if self.current_question
      self.test.questions.order(:id).where('id > ?', current_question.id).first
    else
      test.questions.first
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/passed_tests_controller.rb
class PassedTestsController < ApplicationController
  before_action :set_current_test_passage, only: %i[show update result gist]

  def show
    render locals: {current_test_passage: @current_test_passage}
  end

  def result
  end

  def update
    @current_test_passage.accept!(params[:answer_ids])

    if @current_test_passage.completed?
      TestsMailer.completed_test(@current_test_passage).deliver_now
      BadgeService.new(@current_test_passage).set_badges if @current_test_passage.completed?

      redirect_to result_passed_test_path(@current_test_passage)
    else
      render :show
    end
  end

  def gist
    service = GistQuestionService.new(@current_test_passage.current_question)
    result = service.call

    flash_options =
      if service.success?
        current_user.gists.create(
          question: @current_test_passage.current_question,
          url: result.html_url,
          user: current_user
        )
        { success: I18n.t('passed_tests.gist.success', url: result.html_url) }
      else
        { error: I18n.t('passed_tests.gist.failure') }
      end
    redirect_to @current_test_passage, flash: flash_options
  end

  private

  def set_current_test_passage
    @current_test_passage = PassedTest.find(params[:id])
  end
end

app/helpers/passed_tests_helper.rb
module PassedTestsHelper

  def show_current_question_num_of_total
    I18n.t('.question_num_of_total_html', question_number: @current_test_passage.question_number, total: @current_test_passage.questions_count)
  end

  def test_result
    if @current_test_passage.completed?
      if @current_test_passage.rate_percentage >= PassedTest::TEST_SUCCESS_RATE
        simple_format("#{I18n.t('passed_tests.result_message.passed_test_message')}", {}, wrapper_tag: "h1")
        simple_format("#{t('passed_tests.result.score_message', scores: @current_test_passage.rate_percentage)}", {style: 'color: green'}, wrapper_tag: "h2")
      else
        simple_format("#{I18n.t('passed_tests.result_message.failed_test_message')}", {}, wrapper_tag: "h1")
        simple_format("#{t('passed_tests.result.score_message', scores: @current_test_passage.rate_percentage)}", {style: 'color: red'}, wrapper_tag: "h2")
      end
    end
  end

  def get_progress_percentage
    (((@current_test_passage.question_number - 1) / @current_test_passage.questions_count.to_f) * 100).to_i
  end

  def minutes_left(seconds)
    (Time.mktime(0)+seconds).strftime("%M:%S")
  end
end

app/views/passed_tests/_result_message.slim
= test_result

app/views/passed_tests/result.slim
div class = 'row justify-content-center mt-3'
  .col.col-md-6.col-lg-12
    h1 = I18n.t('passed_tests.result.header', title: @current_test_passage.test.title)
div class = 'card-body'
  = render partial: 'result_message'

app/views/passed_tests/show.slim
.row.justify-content-left.mt-3
  .col.col-md-6.col-lg-12
    h1 = I18n.t('passed_tests.show.title', test_title: @current_test_passage.test.title)
  .card.border-primary
    .card-body
      = show_current_question_num_of_total
      div.progress
        = content_tag :div, class: 'progress-bar', role: 'progressbar', 'aria-valuemin' => 0, 'aria-valuemax' => 100, data: {progress_percentage: get_progress_percentage} do
      .card-mt-3
        .card-body
          = @current_test_passage.current_question.body
      .card-mt-3
        .card-body
          = form_with url: passed_test_path(@current_test_passage), local: true, method: :put do |form|
            = form.collection_check_boxes :answer_ids, @current_test_passage.current_question.answers, :id, :body, include_hidden: false do |b|
              p
                => b.check_box id: "answer_ids_#{b.object.id}"
                = b.label
            = form.submit I18n.t('passed_tests.show.button_next'), class: 'btn btn-primary'
= link_to 'Gist Question', gist_passed_test_path(@current_test_passage), method: :post
- if @current_test_passage.test.timer?
  | |
  =< I18n.t('passed_tests.show.timer')
  =< content_tag(:span, minutes_left(@current_test_passage.time_left), class: "timer", data: { time: @current_test_passage.time_left })