config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :passed_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create] do
    get :new
    post :create
  end

  resources :badges, only: :index

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  CONDITIONS = {
    all_in_category: 0,
    passed_on_first_try: 1,
    all_in_level: 3
  }

  validates :title, :condition, :image, presence: true
  validates :title, uniqueness: true

  before_validation :set_image

  has_many :user_badges, dependent: :destroy

  enum condition: CONDITIONS

  private

  def set_image
    self.image ||= "#{self.condition}.jpg"
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit update destroy]

  def index
    badges = Badge.all
    render locals: {badges: badges}
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :condition, :description)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  def index
    received_badges = current_user.badges
    badges = Badge.all
    render locals: { received_badges: received_badges, badges: badges }
  end
end

app/views/admin/badges/_form.html.slim
= render 'layouts/errors', resource: badge
= form_with model: [:admin, badge], local: true do |f|
  .col
    => f.label :condition
    = f.collection_select :condition, Badge::CONDITIONS, :first, :first, prompt: true
    p
    => f.label :title
    = f.text_field :title, id: :badge_title
    p
    => f.label :description
    = f.text_field :description
    p
    = f.submit

app/views/admin/badges/edit.slim
= render partial: 'form', locals: {badge: @badge}

= link_to I18n.t('.link_to_back'), admin_badges_path

app/views/admin/badges/index.slim
h1
  = I18n.t('admin.badges.index.header')

table.table.table-hover
  thead.thead-dark
    tr
      th = I18n.t('activerecord.attributes.badge.title')
      th = I18n.t('activerecord.attributes.badge.condition')
      th = I18n.t('activerecord.attributes.badge.description')
      th = I18n.t('activerecord.attributes.badge.image')
      th colspan="2" = I18n.t('.actions')
  tbody
    - badges.each do |badge|
      tr
        td = badge.title
        td = I18n.t("activerecord.attributes.badge.conditions.#{badge.condition}")
        td = truncate(badge.description, length: 25)
        td
          button.btn.btn-primary data-toggle="modal" type="button"
            span
              = I18n.t("activerecord.attributes.badge.conditions.#{badge.condition}")
              img.img.hidden src= image_path(badge.image)
        td = link_to I18n.t('.link_to_edit'), edit_admin_badge_path(badge)
        td = link_to I18n.t('.link_to_delete'),
                admin_badge_path(badge),
                method: :delete,
                  data: {confirm: I18n.t('.are_you_sure')}

= link_to I18n.t('link_to_new'), new_admin_badge_path
#Image.modal.fade aria-hidden="true" aria-labelledby="ImageLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      img.img-responsive src= ''

javascript:
 $(document).ready(function () {
   $('.btn').on('click', function () {
       var src = $(this).find('img').attr('src');
       $('#Image img').attr("src", src);
       $('#Image').modal();
   });
 });

app/views/admin/badges/new.slim
= render partial: 'form', locals: {badge: @badge}

= link_to I18n.t('.link_to_back'), admin_badges_path