config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :passed_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create] do
    get :new
    post :create
  end

  resources :badges, only: :index

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAX_ANSWERS = 4

  belongs_to :question
  validates :body, presence: true

  scope :correct, -> { where(correct: true) }

  validate :check_answers_limit, on: :create

  def check_answers_limit
    errors.add(:answers_limit, 'Максимум 4 ответа') if question.answers.count >= MAX_ANSWERS
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_question, only: [:new, :create]

  def show
  end

  def new
    @answer = Answer.new
  end

  def edit
    @question = @answer.question
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to [:admin, @answer.question]
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer.question]
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy

    redirect_to [:admin, @answer.question]
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end

  def set_question
    @question = Question.find(params[:question_id])
  end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.slim
li
  span>
    = answer.body
  span>
    = link_to I18n.t('.link_to_show'), admin_answer_path(answer)
  span>
    = link_to I18n.t('.link_to_edit'), edit_admin_answer_path(answer)
  span>
    = link_to I18n.t('.link_to_delete'), admin_answer_path(answer), method: :delete, data: {confirm: "#{I18n.t('.are_you_sure')}"}

app/views/admin/answers/_form.slim
= form_with model: [:admin, @question, @answer], local: true do |f|
  = render 'layouts/errors', resource: @answer
  = f.label :body
  = f.text_field :body
  = f.label :correct
  = f.check_box :correct, id: :answer_correct
  = f.submit

app/views/admin/answers/edit.html.slim
h1 Редактировать ответ
br
p
  | Вопрос:
  = @answer.question.body
br
= render 'form', locals: {answer: @answer, question: @answer.question}

= link_to I18n.t('.link_to_back'), admin_question_path(@answer.question)

app/views/admin/answers/new.html.slim
h1 Новый ответ

= render 'form'

= link_to I18n.t('.link_to_back'), admin_question_path(@question)

app/views/admin/answers/show.html.slim
h1 Вопрос

p
  = @answer.body
p
  b Правильно:
  = @answer.correct
br
= link_to I18n.t('admin.answers.link_to_add_answer'), admin_question_path(@answer.question)