config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :passed_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create] do
    get :new
    post :create
  end

  resources :badges, only: :index

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/views/layouts/_errors.slim
- if resource.present? && resource.errors.present?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do
  h2
    span>
      = I18n.t('layouts.errors.header', count: resource.errors.count)
  ul
    -resource.errors.full_messages.each do |messege|
      li
        = messege

app/views/layouts/_flash_messages.slim
-flash.each do |name, msg|
 = content_tag :div, msg, class: "flash #{name} alert-dismissible fade show", role: 'alert' do
  = msg

app/views/layouts/_footer.slim
p
  span> Учебный проект в онлайн-школе
  a href = 'http://thinknetica.com/' Thinknetica
  br
  | Автор: Чирков Илья
  br
  | Описание проекта: Портал где создаются тесты с вопросами.
  br
  span> ©
  span>
    = github_url('Thinknetica Test Guru', 'https://github.com/darkelv/test_guru')
  = current_year

app/views/layouts/_navigation.slim
nav class= 'navbar navbar-light bg-light'
  - if user_signed_in?
    = link_to I18n.t('admin.layouts.navigation.title'), current_user.admin? ? admin_tests_path : root_path, class: "navbar-brand"
    = link_to I18n.t('layouts.navigation.leave_feedback'), new_feedback_path, class: "navbar-brand"
    = link_to I18n.t('admin.badges.index.received_badges'), badges_path, class: "navbar-brand"
    span
      => I18n.t('layouts.navigation.welcome_back', username: current_user.name)
      = link_to I18n.t('layouts.navigation.logout_link'), destroy_user_session_path, method: :delete
  - else
    span
      => link_to I18n.t('layouts.navigation.signup'), new_user_registration_path
      = link_to I18n.t('layouts.navigation.login'), new_user_session_path

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= I18n.t('admin.layouts.navigation.link_index_admin_panel') %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'admin/layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/flash_messages' %>
    <%= yield %><br><br>
  </div>
</body>

<%= render 'layouts/footer' %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>ThinknetikaTestGuru</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<%= render 'layouts/navigation' %>

<div class="container">
  <%= render 'layouts/flash_messages' %>
  <%= yield %>
</div>

<div class="card-footer text-muted mt-3">
  <%= render 'layouts/footer' %>
</div>
</body>
</html>